apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-webdav
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: webdav
spec:
  replicas: {{ .Values.webdav.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mailu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: webdav
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mailu.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: webdav
    spec:
      containers:
        - name: {{ .Chart.Name }}-webdav
          image: "{{ .Values.webdav.image.repository }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.webdav.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "mailu.fullname" . }}-env-config
            - secretRef:
                name: {{ template "mailu.fullname" . }}-env-secret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http-ui
              containerPort: 5232
              protocol: TCP
          volumeMounts:
            - name: maildata
              mountPath: /data
              subPath: dav
          resources:
            {{- toYaml .Values.webdav.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: maildata
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "mailu.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
