apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-smtp
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: smtp
spec:
  replicas: {{ .Values.smtp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mailu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: smtp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mailu.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: smtp
    spec:
      containers:
        - name: {{ .Chart.Name }}-smtp
          image: "{{ .Values.smtp.image.repository }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.smtp.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "mailu.fullname" . }}-env-config
            - secretRef:
                name: {{ template "mailu.fullname" . }}-env-secret
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: smtp-ssl
              containerPort: 465
              protocol: TCP
            - name: smtp-starttls
              containerPort: 587
              protocol: TCP
            - name: smtp-auth
              containerPort: 10025
              protocol: TCP
          volumeMounts:
            - name: maildata
              mountPath: /data
              subPath: maildata
            - name: maildata
              mountPath: /overrides
              subPath: overrides
          resources:
            {{- toYaml .Values.smtp.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: maildata
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "mailu.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
