apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mailu.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: admin
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://{{ .Values.mailu.uiHostname }}/admin/ui/"
    ingress.kubernetes.io/follow-redirects: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.mailu.uiHostname  }}
    secretName: {{ .Values.uiCertificateSecretName }}
  rules:
  - host: {{ .Values.mailu.uiHostname  }}
    http:
      paths:
      - path: "/admin"
        backend:
          serviceName: admin
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mailu.fullname" . }}-admin-ui
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: admin
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/ui"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /admin;
spec:
  tls:
  - hosts:
      - {{ .Values.mailu.uiHostname  }}
    secretName: {{ .Values.uiCertificateSecretName }}
  rules:
  - host: {{ .Values.mailu.uiHostname  }}
    http:
      paths:
      - path: "/admin/ui"
        backend:
          serviceName: admin
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mailu.fullname" . }}-admin-static
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: admin
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/static"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /admin;
spec:
  tls:
  - hosts:
    - {{ .Values.mailu.uiHostname  }}
    secretName: {{ .Values.uiCertificateSecretName }}
  rules:
  - host: {{ .Values.mailu.uiHostname  }}
    http:
      paths:
      - path: "/admin/static"
        backend:
          serviceName: admin
          servicePort: http
