apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mailu.fullname" . }}-webdav
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: webdav
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/webdav/(.*) /$1 break;
      auth_request /internal/auth/basic;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      auth_request_set $user $upstream_http_x_user;
      proxy_set_header X-Remote-User $user;
      proxy_set_header X-Script-Name /webdav;
    nginx.ingress.kubernetes.io/server-snippet: |
      location /internal {
        internal;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        proxy_pass http://admin.{{ .Release.Namespace }}.svc.cluster.local;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
      }
spec:
  tls:
  - hosts:
    - {{ .Values.mailu.uiHostname  }}
    secretName: {{ .Values.uiCertificateSecretName }}
  rules:
  - host: {{ .Values.mailu.uiHostname  }}
    http:
      paths:
      - path: "/webdav"
        backend:
          serviceName: webdav
          servicePort: http-ui
