apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mailu.fullname" . }}-antispam
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: security
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/admin/antispam/(.*) /$1 break;
      auth_request /internal/auth/admin;
      proxy_set_header X-Real-IP "";
      proxy_set_header X-Forwarded-For "";
spec:
  tls:
  - hosts:
    - {{ .Values.mailu.uiHostname  }}
    secretName: {{ .Values.uiCertificateSecretName }}
  rules:
  - host: {{ .Values.mailu.uiHostname  }}
    http:
      paths:
      - path: "/admin/antispam"
        backend:
          serviceName: antispam
          servicePort: antispam-http
