apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.admin.serviceType }}
  ports:
    - name: redis
      targetPort: redis
      port: 6379
      protocol: TCP
  selector:
    app: {{ default "redis" .Values.redis.nameOverride | trunc 63 | trimSuffix "-" }}
    release: "{{ .Release.Name }}"
    role: master
