apiVersion: v1
kind: Service
metadata:
  name: webmail
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: webmail
spec:
  type: {{ .Values.webmail.serviceType }}
  ports:
    - name: http
      targetPort: http
      port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webmail
