apiVersion: v1
kind: Service
metadata:
  name: antispam
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: security
spec:
  type: {{ .Values.security.antispam.serviceType }}
  ports:
    - name: antispam
      targetPort: antispam
      port: 11332
      protocol: TCP
    - name: antispam-http
      targetPort: antispam-http
      port: 11334
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: security

---
apiVersion: v1
kind: Service
metadata:
  name: antivirus
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: security
spec:
  type: {{ .Values.security.antivirus.serviceType }}
  ports:
    - name: antivirus
      targetPort: antivirus
      port: 3310
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: security
