apiVersion: v1
kind: Service
metadata:
  name: imap
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: imap
spec:
  type: {{ .Values.imap.serviceType }}
  ports:
    - name: imap-auth
      targetPort: imap-auth
      port: 2102
      protocol: TCP
    - name: imap-transport
      targetPort: imap-transport
      port: 2525
      protocol: TCP
    - name: imap-default
      targetPort: imap-default
      port: 143
      protocol: TCP
    - name: imap-ssl
      targetPort: imap-ssl
      port: 993
      protocol: TCP
    - name: sieve
      targetPort: sieve
      port: 4190
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: imap
