apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |-
{{ .Values.config | indent 4 }}
