{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dex.serviceAccountName" . }}
  labels:
    app: {{ template "dex.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: {{ template "dex.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
