---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs
  namespace: default
spec:
  rules:
  - host: git.lab.thereshope.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: gogs-svc
          servicePort: 80
