apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwt-to-rbac
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jwt-to-rbac-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: default
  name: jwt-to-rbac