{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hostpath-provisioner.fullname" . }}-leader-locking
  labels:
    app.kubernetes.io/name: {{ include "hostpath-provisioner.name" . }}
    helm.sh/chart: {{ include "hostpath-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hostpath-provisioner.fullname" . }}-leader-locking
subjects:
  - kind: ServiceAccount
    name: {{ include "hostpath-provisioner.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
