{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hostpath-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hostpath-provisioner.name" . }}
    helm.sh/chart: {{ include "hostpath-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
