workspace:
  base: /go/src
  path: git.mykube.awesome/gitadmin/example-golang-app

pipeline:
  backend:
    image: golang:1.11.1
    commands:
      - go get -v
      - go get -u github.com/jteeuwen/go-bindata/...
      - /go/bin/go-bindata static/ -o ./assets/bindata.go
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
      - sed -i "s/RELEASE/${DRONE_BUILD_NUMBER}/" ./example-deployment/example-deployment.yaml

  publish_docker:
     image: plugins/docker
     insecure: true
     repo: registry-svc:5000/gitadmin/example-golang-app
     registry: registry-svc:5000
     tags: [ "${DRONE_BUILD_NUMBER}", latest ]

  get_pods:
    image: sokoow/drone-kubectl-helm-clientcert
    secrets: [ kubeconfig_url ]
    kubectl: "get pods"

  deploy_example:
    image: sokoow/drone-kubectl-helm-clientcert
    secrets: [ kubeconfig_url ]
    kubectl: "apply -f example-deployment/example-deployment.yaml"

  deploy_service:
    image: sokoow/drone-kubectl-helm-clientcert
    secrets: [ kubeconfig_url ]
    kubectl: "apply -f example-deployment/example-service.yaml"

  deploy_ingress:
    image: sokoow/drone-kubectl-helm-clientcert
    secrets: [ kubeconfig_url ]
    kubectl: "apply -f example-deployment/example-ingress.yaml"

  get_pods_again:
    image: sokoow/drone-kubectl-helm-clientcert
    secrets: [ kubeconfig_url ]
    kubectl: "get pods"

  write_to_irc:
    image: plugins/irc
    prefix: build
    nick: builder
    channel: kube-desktop
    host: chat.freenode.net
    port: 6667
    template: >
      {{#success build.status}}
        Build success: {{build.link}}, commit:{{build.commit}}
      {{else}}
        Build failure: {{build.link}}, commit:{{build.commit}}
      {{/success}}
