image:
  repository: chocobozzz/peertube
  tag: production-stretch
  pullPolicy: IfNotPresent

ingress:
  tls:
    enabled: false

service:
  type: NodePort
  port: 8084 # PeerTube => P T => 80 84

pvc:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Gi
  storageClass: rook-ceph-block

deps:
  pg:
    managed: false
    password: peertube123
  redis:
    managed: true
  smtp:
    tls:
      enabled: true

postgresql:
  fullnameOverride: peertube-postgresql-1531009616
  postgresDatabase: peertube

redis:
  fullnameOverride: peertube-redis-1531009616
  usePassword: false
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
