---
- hosts: all
  become: true
  any_errors_fatal: true
  gather_facts: false

  pre_tasks:
    - name: Wait for /var/lib/apt/lists/lock
      become: yes
      shell:  while sudo fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Wait for /var/lib/dpkg/lock
      become: yes
      shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - import_tasks: setup.yml
    - import_tasks: packages.yml
