---
- hosts: all
  become: true
  any_errors_fatal: true
  gather_facts: false

  pre_tasks:
# Check for unattended-upgrades
#    - name: Wait for automatic system updates to complete
#      shell: while pgrep unattended; do sleep 10; done;

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - import_tasks: setup.yml
    - import_tasks: packages.yml
