---
# You can add users to the docker group to allow them to manage docker
# containers. This playbook uses sudo rather than the vagrant user because
# Ansible uses ControlPersist for SSH connections. The first time this playbook
# runs, the docker commands would fail if run by the vagrant user, since the
# persisted connection state isn't aware of the addition of the 'docker' group.
- name: Add vagrant user to docker group.
  user:
    name: vagrant
    groups: docker
    append: true

- name: Copy rc.local
  copy:
    src: files/rc.local
    dest: /etc/rc.local
    mode: "0755"

- name: Copy nsswitch.conf
  copy:
    src: files/nsswitch.conf
    dest: /etc/nsswitch.conf

- name: Reload services
  service:
    state: reloaded

- name: Restart service systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Enable service systemd-resolved
  service:
    name: systemd-resolved
    enabled: yes
