apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-agent
    spec:
      hostNetwork: true
      containers:
      - name: drone-agent
        image: sokoow/drone-agent-custom:0.8-alpine
        imagePullPolicy: Always
        env:
        - name: DRONE_SERVER
          # this server value may be different depending on how you set up your kubernetes
          # cluster.  Also if you put it in a different namespace you would use that instead of
          # 'default'.
          value: "127.0.0.1:30100"
        - name: DRONE_SECRET
          value: "bazinga"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        ports:
        - containerPort: 8000
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
