loki:
  enabled: true

promtail:
  enabled: true

fluent-bit:
  enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.4.1

prometheus:
  enabled: true
