{{- if not .Values.deps.pg.managed -}}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: {{ template "peertube.postgresqlSecretName" . }}
  labels:
    app: {{ template "peertube.fullName" . }}
    chart: {{ template "peertube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  postgres-password: {{ required "deps.pg.password required unless deps.pg.managed is true" .Values.deps.pg.password | b64enc | quote }}
{{- end -}}