#!/bin/sh

VER=${DOCKER_LAM_VER:-6.6}
LAM_DIR=${DOCKER_LAM_DIR:-"/wwwroot/lam"}
LAM_PKG=ldap-account-manager-${VER}.tar.bz2
LAM_PKG_DIR="/wwwroot"

install_lam() {
    local PHP_SESSION_DIR=${LAM_DIR}/tmp/session
    [ -d "${PHP_SESSION_DIR}" ] || install -d ${PHP_SESSION_DIR}

    [ -d ${LAM_DIR} ] || install -d ${LAM_DIR}
    local LAM=${LAM_PKG_DIR}/${LAM_PKG%.tar.bz2}
    cd ${LAM}
    ./configure \
        --with-httpd-user=www-data \
        --with-httpd-group=root \
        --with-web-root=${LAM_DIR} \
        --localstatedir=${LAM_DIR}/var \
        --sysconfdir=${LAM_DIR}/etc
    make install
    cd -

    # cd ${LAM_DIR}/config
    # cp config.cfg.sample config.cfg
    # cp unix.conf.sample lam.conf
    # cd -
}


##### main start ####
if [ ! -f "${LAM_DIR}/VERSION" ];then
    set -ex
    install_lam
    set +x
fi

php-fpm


