apiVersion: v1
kind: Service
metadata:
  name: dex-kube
  labels:
    app: {{ template "dex-k8s-authenticator.name" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: {{ template "dex-k8s-authenticator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
{{- if and  .Values.service.nodePort (eq "NodePort" .Values.service.type) }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "dex-k8s-authenticator.name" . }}
    release: {{ .Release.Name }}
