apiVersion: v1
appVersion: "v0.1.0"
description: "Authenticator for using Dex with Kubernetes"
name: dex-k8s-authenticator
version: 0.1.2
sources:
- https://github.com/mintel/dex-k8s-authenticator
maintainers:
- name: Aaron Roydhouse
  email: aaron@roydhouse.com
- name: Nick Badger
  email: nbadger@mintel.com